# config/constants.py
SUMMARY_INTENT_GENERAL = "summary"
SUMMARY_INTENT_FULL = "full_summary"
SUMMARY_INTENT_SECTION = "section_summary"
QUERY_INTENT_DETAIL = "detail"

SUMMARY_INTENT_LABELS = [SUMMARY_INTENT_FULL, SUMMARY_INTENT_SECTION, QUERY_INTENT_DETAIL]